### ISSUE TITLE
Prep sheet on equivalent optimization problems for lasso

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/mlcourse#1]
Several people were confused about the [variable splitting in lasso](https://davidrosenberg.github.io/mlcourse/Archive/2016/Lectures/2b.L1L2-regularization.pdf#page=29) and the meaning of equivalent optimization problems.  Let's create a prep sheet to ease people into this, along the lines of the [svm prep sheet](https://github.com/davidrosenberg/mlcourse/blob/gh-pages/Notes/svm-lecture-prep.pdf).

**Comment by davidrosenberg** [comment]
@brett1479 I feel like your concept check questions may be close to this type of thing.  Do you have some questions that might be good to give in advance of the lecture to build people up to the variable splitting stuff?  People were super confused last year.

**Comment by brett1479** [comment]
Let me know what you think of the first 3 questions here: https://github.com/davidrosenberg/mlcourse-homework/blob/master/in-prep/concept-check-exercises/L1L2Regularization.pdf
Also, should I post it as Lecture 2 Concept Check and then add more to it later, or should it be in a different file PreLecture 2 Concept Check?

**Comment by davidrosenberg** [comment]
Problem 1 is great.  Problem 2 is too hard for a class warmup.  We’d either have to give the solutions (and we’d tell people to understand the solutions before class) or we need to give more hints /steps.   Problem 3… we should ask for a way to map from a minimizer of the new optimization problem to a minimizer of the original optimization problem.

Let's post it as L1/L2 Lecture Prep -- keep it separate.  I'll start a Week 2 block on the webpage.

**Comment by brett1479** [comment]
https://github.com/davidrosenberg/mlcourse-homework/blob/master/in-prep/concept-check-exercises/L1L2Regularization_sol.pdf
If these solutions look good to you I'll push them
