### ISSUE TITLE
Lecture 2a, decision function exists?

### ISSUE THREAD

**Issue by brett1479** [davidrosenberg/mlcourse#16]
Does f_F exist in the decision tree example?

**Comment by davidrosenberg** [comment]
Ha - I guess not since F is not closed.

**Comment by brett1479** [comment]
What is the topology or metric on the space of decision trees?

**Comment by davidrosenberg** [comment]
I wasn't imagining any structure on decision trees themselves, but rather on the prediction functions the trees corresponds to.  So F is a particular set of functions from R^2 to R.  I suspect L2(P_X) norm would make sense here?

**Comment by brett1479** [comment]
Yeah, seems reasonable.  The measure of the region on the square where they differ.
