### ISSUE TITLE
Note on properties of contour plot / tie to subgradient

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/mlcourse#18]
Why are gradient vectors othogonal to contour lines?  Also, what happens at non-differentiable points? What vectors represent subgradients?  Students had difficult time understanding this [subgradient slide](https://davidrosenberg.github.io/mlcourse/Archive/2016/Lectures/4b.subgradient-descent.pdf#page=12), understandably.

**Comment by davidrosenberg** [comment]
Hey @brett1479  -- since you just read the subgradient slides, if you had some thoughts on a slide or two doing a better job of connecting the definition of subgradient to drawing the subgradients on a contour plot, that would be great.

**Comment by brett1479** [comment]
1) What did you want to know about gradients being orthogonal to contours?
2) Suggestion about subgradient slide: One nice image is if you take a subgradient g of a convex function and you draw the line perpendicular to it, then you immediately know that any minimizer must lie on the -g side of the line (or on the line).
3) Directly connected to 2): Even though you mention in class that -g need not be a descent direction, it is true that g is an ascent direction.

**Comment by davidrosenberg** [comment]
1) I just want to post some notes that answer the questions I posed, probably with some proofs.
2) Hmmm - Asymptote that up? ;)  
3) Sounds like a nice little homework exercise.

**Comment by brett1479** [comment]
How's this: https://github.com/davidrosenberg/mlcourse-homework/blob/master/in-prep/recitations/SubgradientFigure.pdf

**Comment by davidrosenberg** [comment]
Yeah! Perfect!  Should the subgradient be (1,b) rather than (3,b)?  Then I believe we'll also see the extreme subgradients being orthogonal to the contour lines. (which would be something to point out in the contour graph note?).

The 3D plot on page 4 is also awesome.  Could we draw the green subgradient arrows in the x1,x2 plane?  And make a bigger dot for the point (v,f(v))?

**Comment by davidrosenberg** [comment]
And the half plane on page 3 can be connected to the idea of subgradients defining supporting hyperplanes for sublevel sets, as described by [Boyd on slides 16,17](http://web.stanford.edu/class/ee364b/lectures/subgradients_slides.pdf#page=17).

**Comment by brett1479** [comment]
Yeah, (1,b) ... good catch.  The PDF should be updated, so let me know what you think.

**Comment by brett1479** [comment]
Yeah, the sublevel set connection is a good idea.

**Comment by brett1479** [comment]
For the gradient orthogonal to contours, I'm guessing you will avoid discussing the implicit function theorem and just say something like: If we have the level surface F(x) = c, and g:(-1,1)->R^n is a curve with non-vanishing derivative then the chain rule says Df(g(0)) g'(0) = 0 proving the gradient is orthogonal to the tangent to the contour.  [In other words, the tangent space of the manifold is the kernel of Df.]

**Comment by brett1479** [comment]
I also added a PRC figure to the PDF above so if you open it in Acrobat Reader, it should be zoom/pannable.
