### ISSUE TITLE
Lecture 3c Slide 17 Comment

### ISSUE THREAD

**Issue by brett1479** [davidrosenberg/mlcourse#19]
I don't think the fact that w is a linear combination of the xi vectors is a surprising fact that we obtained from the analysis.  I believe that follows immediately from the statement of the primal problem.  What makes the linear combination result a bit more interesting is that the coefficients on the xi have a fixed sign.

**Comment by brett1479** [comment]
Another point is that before we wrote w* = sum a_i* y_ix_i, we didn't know how to turn dual solutions into primal solutions (at least for the w part, b later).

**Comment by davidrosenberg** [comment]
That's interesting -- I actually don't know why it's immediate from the primal problem that w is a linear combination of the x_i vectors.  Is there a way to show it that's easier than the representer theorem?  Do tell!

**Comment by brett1479** [comment]
Assuming I have the primal problem correct, write w = wx + wx' where wx is in the span of the xi's, and wx' is in the orthogonal complement.  Then wx' has no effect on the decision function and only increases the l2-regularization term.

**Comment by davidrosenberg** [comment]
And that's the proof of the representer theorem.

**Comment by brett1479** [comment]
Yeah, I guess it is.  That said, I think it is much more direct than Lagrange duality (and in particular, the strong duality we used).

**Comment by davidrosenberg** [comment]
For SVM, I think the main payoff of strong duality is this set of results on the [relation between the dual solution and the margin](https://davidrosenberg.github.io/mlcourse/Archive/2016/Lectures/3c.SVM.pdf#page=23).  And for the class as a whole, the only additional thing is the equivalence of the norm penalization and bounded norm forms of regularization.  It'd be nice if we could get more from it, so long as we're teaching it anyway.

**Comment by brett1479** [comment]
Yeah, I agree.  I just meant that the fact that w is a linear combination of the xs follows from much less than the strong duality.

**Comment by davidrosenberg** [comment]
Yeah I agree.  And once you know w is a linear combination of x's, the fact that you can kernelize follows immediately.  Yet for years everybody "derived" kernelization for SVM via the dual.
