### ISSUE TITLE
Making text-based / flow chart figures

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/mlcourse#25]
Any suggestions on how to make figures like these: (would you use Asymptote?)
https://github.com/davidrosenberg/mlcourse/blob/gh-pages/Figures/features/emailFeatures.png
https://github.com/davidrosenberg/mlcourse/blob/gh-pages/Figures/features/feature-extraction.png

**Comment by brett1479** [comment]
Asymptote will work, although it could be very quick to make those types of figures in a GUI based vector graphics tool.  I have never used Inkscape, but I imagine it would quickly make them.

**Comment by davidrosenberg** [comment]
Yeah...

**Comment by brett1479** [comment]
What tool was used to make those?

**Comment by davidrosenberg** [comment]
Email features is from Percy's class, so I guess he used his own javascript stuff.  The feature-extraction one I think I made years ago in PowerPoint with a plug-in that made it easy to paste in compiled latex equations as images....
