### ISSUE TITLE
Shanshan's differentiation handout has a bug?

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/mlcourse#3]
[Shanshan's notes](https://davidrosenberg.github.io/ml2015/docs/matrix-differentiation.pdf) may have a small bug in them, for differentiating the quadratic form

 https://piazza.com/class/ii99b8o57me5jo?cid=30

**Comment by brett1479** [comment]
I think it makes sense to retire this document and incorporate some of the ideas into a PDF of notes/not-to-be-submitted exercises that will accompany the first lab.
