### ISSUE TITLE
Directional Derivatives vs Differentiability

### ISSUE THREAD

**Issue by brett1479** [davidrosenberg/mlcourse#31]
Let f:R^2->R be given by f(x,y) = x if y = x^2 and 0 otherwise.  Then f is continuous at (0,0) and all directional derivatives there are zero but f is not differentiable at (0,0).  In this example, we have non-differentiability even though we have a vector (the zero vector) that "behaves" like a gradient with respect to giving the directional derivatives upon taking inner products with the direction.

**Comment by davidrosenberg** [comment]
Great example - thanks!
