### ISSUE TITLE
Learning objectives for Lab #1

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/mlcourse#32]
Write learning objectives for Lab #1.  Learning objectives should be somewhat testable.  Something more specific than "understand X".  I currently have this in learning-objectives.org, but feel free to start a learning-objectives.md file instead.  Seems more standard.

**Comment by brett1479** [comment]
I am a little confused about this file.
1) Do the students get access to it, and is it posted somewhere on the course website?  Who is the intended consumer?
2) Do I just copy what is currently in learning-objectives.org into learning-objectives.md (it seems like a single file and not 1 per lecture/lab), and then append the first lab stuff to it?

**Comment by davidrosenberg** [comment]
It's for students, to let them know what they could potentially be tested on.  It's basically a study guide.  It will eventually be referenced on the course website.

**Comment by davidrosenberg** [comment]
I don't care much about the format -- it's easy to change later. I just want to get the content down.  You can copy the org to MD, or just start a new md file with just your stuff, or continue the org file.

**Comment by brett1479** [comment]
Updated.
