### ISSUE TITLE
More on Elastic Net Picture

### ISSUE THREAD

**Issue by brett1479** [davidrosenberg/mlcourse#36]
In the lab you give a picture proof that L2 regularization sets the coefficients to be equal when you have a duplicated feature.  I think it makes sense to continue the picture discussion and see what happens when you use L1 regularization.

**Comment by davidrosenberg** [comment]
Yeah this would be great -- could you whip up some asymptote illustrating?  You could make the level sets of w_1 + w_2 = c, until they hit the L1 or L2 norm ball.  While we're at it, we could also take x_1 = 2x_2, to get level sets of 2w1+w2=c, to show that Lasso would select x1 while ridge would mix.   And this is also the answer to my question on what the heck is that quora illustration showing.

**Comment by brett1479** [comment]
Here are drawings with no labels.  Let me know if you want anything else on them (labels, other markup).
https://github.com/davidrosenberg/mlcourse-homework/tree/master/in-prep/recitations/L1vL2

**Comment by davidrosenberg** [comment]
These are great.  Let's change the axes labels to w_1 and w_2, and give the equations for a few of the lines (as you did for the SVM), and also give the expression for the norm balls (so we know the radius).  Thanks!

**Comment by brett1479** [comment]
Do we want the pictures all at the same scale?  At the moment I just picked convenient radii for the norm-balls so the contour lines intersect them, but I could fix the radii and change the contours accordingly.

**Comment by davidrosenberg** [comment]
Not really sure.  I guess I'd have to see it and think about how I'd
present it...

**Comment by brett1479** [comment]
Take a look now: https://github.com/davidrosenberg/mlcourse-homework/tree/master/in-prep/recitations/L1vL2
