### ISSUE TITLE
Feature Slides

### ISSUE THREAD

**Issue by brett1479** [davidrosenberg/mlcourse#37]
Is vector quantization an important enough feature generation method to discuss?

**Comment by davidrosenberg** [comment]
I think it's very important.  I understand it as clustering with the intent to use the cluster assignment as a feature.  If you some development of that idea, we can include that in the feature lectures.

**Comment by davidrosenberg** [comment]
@bjakubowski - this is something to consider for the Features Lab.

**Comment by davidrosenberg** [comment]
I think @bjakubowski 's new feature slides https://github.com/davidrosenberg/mlcourse/blob/gh-pages/Labs/4-Features/tex/04e.features.pdf (cf4ba1404e32f2aae2a63fa01dd68dbeee0ff781) addresses this, but doesn't actually use the term "vector quantization".  @bjakubowski do you want to work that term in?

**Comment by davidrosenberg** [comment]
Done.
