### ISSUE TITLE
Geometric margin vs... margin

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/mlcourse#4]
If we discuss the "margin" in the hard-margin SVM setting, it's important to distinguish this geometric margin from the usual margin (which is just score x label for 2-class).

**Comment by brett1479** [comment]
The geometric margin is the minimum over y_i(w^T x_i + b)/ ||w||.  The margin is the numerator.  Is this the distinction you had in mind?

**Comment by davidrosenberg** [comment]
Yeah - for the case of affine prediction functions, the margin on x_i,y_i is the numerator.
