### ISSUE TITLE
Clean up mlcourse for archiving

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/mlcourse#43]
Brett -- I think you over-committed some that shouldn't be in the repos.  Can you remove those, and also any cleanup you want to do before I make a 2017 archive?

**Comment by brett1479** [comment]
I cleaned up some files.  Not sure if the ones I cleaned up are the ones you're referring to.

**Comment by davidrosenberg** [comment]
Thanks! Do we need the .out files? There's also something like Varfill.tex?

**Comment by brett1479** [comment]
Out, no, varfill, yes

**Comment by davidrosenberg** [comment]
Varfill.ltx seems like a dup of 13-PCA-Slides.ltx?

**Comment by brett1479** [comment]
VarFill is a file used by my build system while I am making the pdf files.
I can get rid of it if you want.

**Comment by davidrosenberg** [comment]
I think if it autogenerates it shouldn't be in the repo. Am I missing something?

**Comment by brett1479** [comment]
Removed them.

**Comment by davidrosenberg** [comment]
Thanks!
