### ISSUE TITLE
Are these actually subgradients in the figure?

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/mlcourse#45]
https://github.com/davidrosenberg/mlcourse/blob/bb0d258d8784c3b32ce37b88299d02063cadb029/Labs/4-Subgradients-Notes.ltx#L123

are they the underestimating functions associated with the subgradients?

**Comment by brett1479** [comment]
Yeah, those aren't the subgradients (which are real numbers).  They are the global underestimating hyperplanes.
