### ISSUE TITLE
Update lecture 2 concept checks

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/mlcourse#58]
Besides the usual formatting change, there's a reference to a 'beta' vector in one of the questions about the lasso/ridge regularization path plots.  I've changed it to w in the plot, so we should change that variable...

**Comment by bjakubowski** [comment]
Done- note I didn't add all the L1/L2 objectives to this check, since the concept checks don't get into sparsity/regularization paths/etc.
