### ISSUE TITLE
Link to Felippa's Matrix Calculus is incorrect/outdated

### ISSUE THREAD

**Issue by brett1479** [davidrosenberg/mlcourse#6]
Should be http://www.colorado.edu/engineering/cas/courses.d/IFEM.d/IFEM.AppC.d/IFEM.AppC.pdf

**Comment by davidrosenberg** [comment]
Where are you seeing the bad link? The link seems to work for me on ml2015 and ml2016 course pages.

**Comment by brett1479** [comment]
On the main page of http://davidrosenberg.github.io/ml2016/#lectures I traverse the link: http://www.colorado.edu/engineering/cas/courses.d/IFEM.d/IFEM.AppF.d/IFEM.AppF.pdf and it takes me to a document about Fitting Element Fields.  The link I gave earlier goes to Linear Algebra: Matrix Calculus.  Am I clicking the wrong thing?

**Comment by davidrosenberg** [comment]
Got it -- thanks! Done...
